name: Service Action Workflow

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Select the service'
        type: choice
        default: 'default-px'
        options:  ['service-1']

jobs:
  generate-service-options:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


