name: Sequential Jobs with Confirmation

on:
  workflow_dispatch:
    inputs:
      proceed:
        description: 'Do you want to proceed with the second job?'
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: First job step
        run: echo "This is the first job."

  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    if: github.event.inputs.proceed == 'yes'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Second job step
        run: echo "This is the second job."
