name: Sequential Jobs with Confirmation

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: First job step
        run: echo "This is the first job."

      - name: Request user confirmation
        id: confirm
        run: |
          echo "Do you want to proceed with the second job? (yes/no)"
          read answer
          echo "::set-output name=confirm::${answer}"

  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    if: needs.first-job.outputs.confirm == 'yes'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Second job step
        run: echo "This is the second job."
