name: Second Job

on:
  workflow_dispatch:
  issues:
    types: [labeled]

jobs:
  job2:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run second job
        run: echo "Second job is running..."
