name: Second Job

on:
  issue_comment:
    types: [created]

jobs:
  job2:
    if: ${{ github.event.comment.body == 'yes' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run second job
        run: echo "Second job is running..."
